<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="windows_desktop_app\**\*.cs" />
    <EmbeddedResource Remove="windows_desktop_app\**\*" />
    <None Remove="windows_desktop_app\**\*" />
  </ItemGroup>
</Project>
